# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/rafaelarce/Library/CloudStorage/Box-Box/uprrp/cursos/ccom3034/c52/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/rafaelarce/Library/CloudStorage/Box-Box/uprrp/cursos/ccom3034/c52/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rafaelarce/Library/CloudStorage/Box-Box/uprrp/cursos/ccom3034/c52/src/CMakeFiles /Users/rafaelarce/Library/CloudStorage/Box-Box/uprrp/cursos/ccom3034/c52/src//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rafaelarce/Library/CloudStorage/Box-Box/uprrp/cursos/ccom3034/c52/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hello_imtui

# Build rule for target.
hello_imtui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello_imtui
.PHONY : hello_imtui

# fast build rule for target.
hello_imtui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_imtui.dir/build.make CMakeFiles/hello_imtui.dir/build
.PHONY : hello_imtui/fast

#=============================================================================
# Target rules for targets named bouncing_ball_imtui

# Build rule for target.
bouncing_ball_imtui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bouncing_ball_imtui
.PHONY : bouncing_ball_imtui

# fast build rule for target.
bouncing_ball_imtui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bouncing_ball_imtui.dir/build.make CMakeFiles/bouncing_ball_imtui.dir/build
.PHONY : bouncing_ball_imtui/fast

#=============================================================================
# Target rules for targets named bouncing_ball_imtui_circle

# Build rule for target.
bouncing_ball_imtui_circle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bouncing_ball_imtui_circle
.PHONY : bouncing_ball_imtui_circle

# fast build rule for target.
bouncing_ball_imtui_circle/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bouncing_ball_imtui_circle.dir/build.make CMakeFiles/bouncing_ball_imtui_circle.dir/build
.PHONY : bouncing_ball_imtui_circle/fast

#=============================================================================
# Target rules for targets named imgui-for-imtui

# Build rule for target.
imgui-for-imtui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui-for-imtui
.PHONY : imgui-for-imtui

# fast build rule for target.
imgui-for-imtui/fast:
	$(MAKE) $(MAKESILENT) -f imtui/third-party/CMakeFiles/imgui-for-imtui.dir/build.make imtui/third-party/CMakeFiles/imgui-for-imtui.dir/build
.PHONY : imgui-for-imtui/fast

#=============================================================================
# Target rules for targets named imtui

# Build rule for target.
imtui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imtui
.PHONY : imtui

# fast build rule for target.
imtui/fast:
	$(MAKE) $(MAKESILENT) -f imtui/src/CMakeFiles/imtui.dir/build.make imtui/src/CMakeFiles/imtui.dir/build
.PHONY : imtui/fast

#=============================================================================
# Target rules for targets named imtui-ncurses

# Build rule for target.
imtui-ncurses: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imtui-ncurses
.PHONY : imtui-ncurses

# fast build rule for target.
imtui-ncurses/fast:
	$(MAKE) $(MAKESILENT) -f imtui/src/CMakeFiles/imtui-ncurses.dir/build.make imtui/src/CMakeFiles/imtui-ncurses.dir/build
.PHONY : imtui-ncurses/fast

bouncing_ball_imtui.o: bouncing_ball_imtui.cpp.o
.PHONY : bouncing_ball_imtui.o

# target to build an object file
bouncing_ball_imtui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bouncing_ball_imtui.dir/build.make CMakeFiles/bouncing_ball_imtui.dir/bouncing_ball_imtui.cpp.o
.PHONY : bouncing_ball_imtui.cpp.o

bouncing_ball_imtui.i: bouncing_ball_imtui.cpp.i
.PHONY : bouncing_ball_imtui.i

# target to preprocess a source file
bouncing_ball_imtui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bouncing_ball_imtui.dir/build.make CMakeFiles/bouncing_ball_imtui.dir/bouncing_ball_imtui.cpp.i
.PHONY : bouncing_ball_imtui.cpp.i

bouncing_ball_imtui.s: bouncing_ball_imtui.cpp.s
.PHONY : bouncing_ball_imtui.s

# target to generate assembly for a file
bouncing_ball_imtui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bouncing_ball_imtui.dir/build.make CMakeFiles/bouncing_ball_imtui.dir/bouncing_ball_imtui.cpp.s
.PHONY : bouncing_ball_imtui.cpp.s

bouncing_ball_imtui_circle.o: bouncing_ball_imtui_circle.cpp.o
.PHONY : bouncing_ball_imtui_circle.o

# target to build an object file
bouncing_ball_imtui_circle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bouncing_ball_imtui_circle.dir/build.make CMakeFiles/bouncing_ball_imtui_circle.dir/bouncing_ball_imtui_circle.cpp.o
.PHONY : bouncing_ball_imtui_circle.cpp.o

bouncing_ball_imtui_circle.i: bouncing_ball_imtui_circle.cpp.i
.PHONY : bouncing_ball_imtui_circle.i

# target to preprocess a source file
bouncing_ball_imtui_circle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bouncing_ball_imtui_circle.dir/build.make CMakeFiles/bouncing_ball_imtui_circle.dir/bouncing_ball_imtui_circle.cpp.i
.PHONY : bouncing_ball_imtui_circle.cpp.i

bouncing_ball_imtui_circle.s: bouncing_ball_imtui_circle.cpp.s
.PHONY : bouncing_ball_imtui_circle.s

# target to generate assembly for a file
bouncing_ball_imtui_circle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bouncing_ball_imtui_circle.dir/build.make CMakeFiles/bouncing_ball_imtui_circle.dir/bouncing_ball_imtui_circle.cpp.s
.PHONY : bouncing_ball_imtui_circle.cpp.s

hello_imtui.o: hello_imtui.cpp.o
.PHONY : hello_imtui.o

# target to build an object file
hello_imtui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_imtui.dir/build.make CMakeFiles/hello_imtui.dir/hello_imtui.cpp.o
.PHONY : hello_imtui.cpp.o

hello_imtui.i: hello_imtui.cpp.i
.PHONY : hello_imtui.i

# target to preprocess a source file
hello_imtui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_imtui.dir/build.make CMakeFiles/hello_imtui.dir/hello_imtui.cpp.i
.PHONY : hello_imtui.cpp.i

hello_imtui.s: hello_imtui.cpp.s
.PHONY : hello_imtui.s

# target to generate assembly for a file
hello_imtui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_imtui.dir/build.make CMakeFiles/hello_imtui.dir/hello_imtui.cpp.s
.PHONY : hello_imtui.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bouncing_ball_imtui"
	@echo "... bouncing_ball_imtui_circle"
	@echo "... hello_imtui"
	@echo "... imgui-for-imtui"
	@echo "... imtui"
	@echo "... imtui-ncurses"
	@echo "... bouncing_ball_imtui.o"
	@echo "... bouncing_ball_imtui.i"
	@echo "... bouncing_ball_imtui.s"
	@echo "... bouncing_ball_imtui_circle.o"
	@echo "... bouncing_ball_imtui_circle.i"
	@echo "... bouncing_ball_imtui_circle.s"
	@echo "... hello_imtui.o"
	@echo "... hello_imtui.i"
	@echo "... hello_imtui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

